#!/bin/sh

# run the tests and checkstyle with the gradle wrapper
./gradlew checkstyleMain
./gradlew checkstyleTest

# store the last exit code in a variable
RESULT=$?

# return the './gradlew test' exit code
exit $RESULT